### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by giordy** [tors42/chariot#1]
Hello!

I was considering creating a Lichess-based toy project in Android and your library would be super useful and pretty much ready to use for interfacing to Lichess APIs 🚀

There's a small issue preventing me from doing that though, the compiled jar available via maven uses bytecode for Java 17, while android supports only libraries compiled for Java 11 and below, at the moment.
Would you consider distributing the jar compiled for Java 11? Or in case providing an alternate artifact for Android, in case 🤔 

Thanks for your work!

**Comment by tors42** [comment]
Hi!

In the current state it is sadly not possible to achieve by such an easy means as to just specify the number 11.
(If that was the case, I'd immediately do it.)

Since Java 9 it _is_ possible to use a parameter `--release <release>` to the Java compiler,
to tell it which Java release to compile for.
So theoretically it is possible to compile for Java 11 when using a Java 17 compiler.

But for `--release 11` to work,
the source code can't contain features which doesn't exist in Java 11.

I did a quick non-scientific test to compile the current source code for older versions,
to see what the "initial reported damage" is:

`--release 16`
42 errors

`--release 15`
633 errors

`--release 14`
634 errors

`--release 11`
645 errors

The Java features beyond 11 in the current code base are roughly:

Major usages:
"sealed classes"         - Java 17
"records"                - Java 16
"switch expressions"     - Java 12

Minor usages:
Basic "pattern matching" - Java 16
"text blocks"            - Java 15

So in order to be able to introduce Java 11 support,
one would need to add Java 11 source code for all the places where these newer features are used.   
                                                                                                    
Pros:                                                                                               
 - Run in many more environments (such as Android)                                                  
 - Learning experience to use (probably) Multi-Release jars                                         
                                                                                                    
Cons:                                                                                               
 - It would take (unknown amount of) time to add the existing functionality again, but using older features
 - The project complexity would increase with the need to support also older versions               

So I must disappoint you that I can't easily deploy a Java 11 version any time soon. :(

**Comment by giordy** [comment]
Thanks for the very extended response!
I totally understand, it's definitely quite some work, I'm closing the issue 👍🏻
