### ISSUE TITLE
addGamesIdToStream sometimes throws an IOException

### ISSUE THREAD

**Issue by JohnChernoff** [tors42/chariot#19]
The following (apparently unhandled?) error seems to occasionally occur when using games() methods:

Nov 12, 2024 4:28:55 AM chariot.internal.InternalClient request
SEVERE: https://lichess.org/api/stream/games/chess_center638/add POST
java.io.IOException: /[redacted IP]:49534: GOAWAY received
	at java.net.http/jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:969)
	at java.net.http/jdk.internal.net.http.HttpClientFacade.send(HttpClientFacade.java:133)
	at chariot.internal.InternalClient.sendRequest(InternalClient.java:216)
	at chariot.internal.InternalClient.sendWithRetry(InternalClient.java:150)
	at chariot.internal.InternalClient.request(InternalClient.java:101)
	at chariot.internal.RequestParameters$ReqOne.process(RequestParameters.java:35)
	at chariot.internal.impl.GamesHandler.addGameIdsToStream(GamesHandler.java:109)

(etc)

**Comment by tors42** [comment]
Hi!

Hmm, some network error seems to be happening...

The text you've pasted is the logging output generated by the logging statement in the below `catch`-block,
https://github.com/tors42/chariot/blob/796cf191c3a859e5d678580c845dae9acaaeb132/src/main/chariot/chariot/internal/InternalClient.java#L100-L105

Javas default logging configuration can be found in `$JAVA_HOME/conf/logging.properties`,
i.e the configuration file controls where logging output shows up.
When I look in that file in my JDK, it looks like all logging at level `INFO` and "higher" will be logged to Console.
The chariot code sets the severity level as `SEVERE` for this log.

After the exception has been logged,
a failure response is returned to the user (you 😄).

To detect the failure,
you could do something like this when you invoke the API 

```java
    import chariot.model.One;
    import chariot.model.Fail;

    ...

    One<Void> result = client.games().addGameIdsToStream("my-stream-id", Set.of("gameid1", "gameid2", "gameid3");

    if (result instanceof Fail(int statusCode, var err)) {
        System.out.println("Doh! Request to add game failed!");
        System.out.println("HTTP Status Code: " + statusCode);
        System.out.println("Error message: " + err.message());
        return;
    }

    ...
```

Oh, and back to the logging,
it is also possible to change the logging levels of chariot programatically, like so:
```java
    var client = Client.basic();
    client.logging(l -> l.request().all()); // enable debug logging of all outgoing requests
    client.logging(l -> l.response().off()); // disable any logs about responses.
```

Enabling logging for the responses can be nice in order to see the response bodies and response headers from Lichess, i.e to get copy/paste:able JSON - in case Lichess updates and includes more information than chariot is currently able to model...

**Comment by tors42** [comment]
Uhm, my example code seems bad for this example by the way, i.e
```java
System.out.println("HTTP Status Code: " + statusCode);
```
In this case it is the connection which gets closed - so it isn't a failure based on a non-`2xx` HTTP status code but communication failure (so value `-1` will be used in this case...)

**Comment by JohnChernoff** [comment]
Aha, thanks, I'll try that.   Not yet sure why the error is occurring in the first place but at least it's catchable, yay

**Comment by tors42** [comment]
I guess Lichess server sends a `GOAWAY` message to the client.

Hmm, according to https://www.rfc-editor.org/rfc/rfc7540#section-6.8 ,
```
The GOAWAY frame also contains a 32-bit error code (Section 7) that
contains the reason for closing the connection.
```

https://www.rfc-editor.org/rfc/rfc7540#section-7

I guess it is possible to check in Wireshark what the GOAWAY frame looks like, maybe the 32-bit error code reveals something.

Here's a repo, https://github.com/neykov/extract-tls-secrets , which can be used to extract the TLS secrets from the JVM during the handshake, so one can analyze the traffic in Wireshark decrypted.

I've seen GOAWAY frames too, when running a Lichess BOT - https://github.com/tors42/charibot/ - but I haven't been curious/non-lazy enough to diagnose it... 😊

I just go with network disconnections happen - we deal with it... 😅
