### ISSUE TITLE
Can I configure the endpoint?

### ISSUE THREAD

**Issue by lakinwecker** [tors42/chariot#5]
If I wanted to use this library with another lichess-clone, can I configure it to use that endpoint?

**Comment by tors42** [comment]
I guess it would work, yes:
`Client client = Client.basic(c -> c.api("https://clone.org"));`

`ClientAuth clientAuth = Client.auth(c -> c.api("https://clone.org").auth("my-token"));`

Oh, and explorer+tablebase:
`Client client = Client.basic(c -> c.api("https://clone.org").servers(s -> s.explorer("https://explorer.lichess.ovh").tablebase("https://tablebase.lichess.ovh"));`

**Comment by tors42** [comment]
After some more thinking,
this library models the LIchess API with a set of data types specific for Lichess,
so depending on how much the "lichess-clone" differs,
the data types might be too strict and not match the clone layout.

For instance,
there's some usages of Enums:
https://github.com/tors42/chariot/blob/f8e66b426ee480604ef6d03225089c691f21837d/src/main/chariot/chariot/model/Enums.java#L98-L107
I guess a "lichess-clone" could have more variants so that would cause a failure with this library.
Had the fields been modeled with a less striclty typed String instead, it would have worked better with "unexpected" values...

There is no support today to provide custom datatypes from "user-land",
but I guess that could be a nice feature.
A couple of use cases:
 - "lichess-clone"s could override the default data models with "user-land" models.
 - If Lichess server-side changes some layout, one can start using the new layout with help of "user-land" models (while waiting for a new Chariot release with the updated models)

**Comment by lakinwecker** [comment]
Yeah, lichess clones are likely to have different features (like variants), so I can understand why this might not be as simple as it first sounds.

**Comment by tors42** [comment]
chariot-0.0.47 / a8190f3 adds rudimentary support for custom endpoints.

Example with raw json response:
```java
    var client = Client.basic(c -> c.api("https://api.chess.com"));

    var endpointJson = client.custom()
        .of(Function.identity())
        .path("/pub/player/%s")
        .toOne();

    String string1 = endpointJson.request(req -> req.path("hikaru"))
        .map(json -> "Raw: " + json)
        .orElse("No such user!");

    System.out.println("string1: " + string1);
```
Output:
```
string1: Raw: {"avatar":"https://images.chesscomfiles.com/uploads/v1/user/15448422.90503d66.200x200o.f323efa57fd0.jpeg","player_id":15448422,"@id":"https://api.chess.com/pub/player/hikaru","url":"https://www.chess.com/member/Hikaru","name":"Hikaru Nakamura","username":"hikaru","title":"GM","followers":974520,"country":"https://api.chess.com/pub/country/US","location":"Sunrise, Florida","last_online":1660335340,"joined":1389043258,"status":"premium","is_streamer":true,"twitch_url":"https://twitch.tv/gmhikaru","verified":true}
```

And an example of a custom model (partial fit of model):
```java
    ...

    record PlayerProfile(String url, int followers) {}

    var endpointModel = client.custom()
        .of(PlayerProfile.class)
        .path("/pub/player/%s")
        .toOne();

    String string2 = endpointModel.request(req -> req.path("hikaru"))
        .map(profile -> profile.url() + " " + profile.followers())
        .orElse("No such user!");

    System.out.println("string2: " + string2);
```
Output:
```
string2: https://www.chess.com/member/Hikaru 974520
```
